name: Ensure Code Formatting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install pycodestyle autopep8
          python -m pip install -e .
      
      - name: Check Errors
        run: |
          pycodestyle --statistics --count --max-line-length=150 --show-source .